---
title: "R Notebook"
output: html_notebook
---

# Fontes:

Samples_docapesca_for_PNAB_summary_1_comprimentos.csv: enviado pela Rita por mail

```{r}
library(ggplot2)
library(dplyr)
library(gt)
```

```{r}
df = read.csv('data/Samples_docapesca_for_PNAB_summary_1_comprimentos.csv')
fao = c('GUU','GUR','GUM','GUN','GUG','CTZ','LDV','LEP')
```

# Por especie amostrada

```{r}
df %>%
  filter(especie_am %in% fao) %>%
  group_by(denominacao, especie_am) %>%
  summarise(n = sum(SUM_n_nao_observados), na.rm = T)
```

# Por denominacao

```{r}
df %>%
  filter(denominacao %in% fao) %>%
  group_by(denominacao, especie_am) %>%
  summarise(n = sum(SUM_n_nao_observados), na.rm = T)
```

```{r}
df %>%
  filter(especie_am %in% fao) %>%
  group_by(denominacao, especie_am) %>%
  summarise(n = sum(SUM_n_nao_observados), na.rm = T) %>%
  gt %>%
  tab_header(
    title = md('olha que coisa **gira** que eu fiz'),
    subtitle = 'btw isto sao dados do fishmetrics') %>%
  tab_source_note(md('*Gostas*?'))

```

```{r}
iris %>% gt
```





